export default [
  {
    name: 'Aarav Mehta',
    year: 2024,
    photoUrl: '',
    state: 'Maharashtra',
    score: '94.2%',
    description: 'First-year engineering student passionate about renewable energy.',
    bio: 'Aarav grew up in a small village and is the first in his family to attend college. He hopes to bring clean energy solutions back to his community.',
    achievements: ['District-topper in Class XII', 'Recipient of the State Merit Scholarship'],
  },
  {
    name: 'Priya Sharma',
    year: 2024,
    photoUrl: '',
    state: 'Rajasthan',
    score: '91.6%',
    description: 'Aspiring physician focused on rural healthcare access.',
    bio: 'Priya volunteers at her local health camp every summer and dreams of opening a clinic in her hometown.',
    achievements: ['Volunteer, Rural Health Camp', 'Merit certificate in Biology Olympiad'],
  },
  {
    name: 'Rohan Verma',
    year: 2023,
    photoUrl: '',
    state: 'Uttar Pradesh',
    score: '89.8%',
    description: 'Computer science student building assistive technology.',
    bio: 'Rohan built a low-cost screen reader for visually impaired students in his school as a class project.',
    achievements: ['Winner, State Science Fair 2022'],
  },
  {
    name: 'Sneha Kulkarni',
    year: 2023,
    photoUrl: '',
    state: 'Maharashtra',
    score: '93.1%',
    description: 'Studying environmental science with a focus on water conservation.',
    bio: 'Sneha leads a youth group that restored a local pond used by over 200 families for irrigation.',
    achievements: ['Youth Environmental Leadership Award'],
  },
  {
    name: 'Karan Singh',
    year: 2022,
    photoUrl: '',
    state: 'Madhya Pradesh',
    score: '87.4%',
    description: 'First-generation learner pursuing a degree in commerce.',
    bio: 'Karan supports his family business while studying and hopes to expand it into a registered enterprise.',
    achievements: [],
  },
  {
    name: 'Neha Joshi',
    year: 2022,
    photoUrl: '',
    state: 'Gujarat',
    score: '90.5%',
    description: 'Studying education, aiming to teach in under-resourced schools.',
    bio: 'Neha tutors younger students in her neighbourhood for free every weekend.',
    achievements: ['Certificate of Excellence in Teaching Practicum'],
  },
];
